### ISSUE TITLE
[Bug]: not able to add SubmodelElementCollection to SubmodelElementList

### ISSUE THREAD

**Issue by jh-isw** [rwth-iat/aas_manager#20]
### What happened?

Hello,
I wanted to add a SubmodelElementCollection (SMC) to a SubmodelElementList (SML).

IDTA-01001-3-0 Specification -> Constraint AASd-120 states, that an element of a SML should not have an IdShort. Yet, I can't add a SMC without supplying an IdShort.

Here's the error I get, when supplying no IdShort:

![image](https://github.com/rwth-iat/aas_manager/assets/26556312/337d3a3e-b196-4f62-b446-c42663b04985)

**Comment by zrgt** [comment]
Hey @jsw, big thanks for spotting that bug! 🌟 We've fixed it in the latest release, which you can check out here: https://github.com/rwth-iat/aas_manager/releases/tag/7241236642 

Because the idShort for all Referables SEs is mandatory except for SEs in SubmodelElementLists, we had to do some hack, such that idShort of SE in SEList can not be provided by the user, but will be generated automatically and removed while serialisation .

Your report helped us a lot. Feel free to report any other issues you come across. It's super helpful and keeps our software getting better. Thanks again!

**Comment by zrgt** [comment]
Fixed in 3ba7942a78e400218a1e99249359cb546488894a
